baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sho Takishita (瀧下 祥)'
theme = "m10c"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "Publication"
    name = "Publication"
    url = "/tags/"
    weight = 2

[params]
  author = "John Doe"
  description = "Reseacher@Fujitsu LTD."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/sh-tkst"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/kengrgrgr"

  [[params.social]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/sho-takishita-39958b17b/"

  [[params.social]]
    icon = "twitter"
    name = "tabler mail"
    url = "sho.takish@gmail.com"

  author = "Sho Takishita"
  description = "Sho Takishita."

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
   [params.style]
    darkestColor = "#315659"
    darkColor = "#253031"
    lightColor =  "#ffffff"
    lightestColor = "#fff"
    primaryColor = "#ffffff"

  # Red theme
  # [params.style]
#    darkestColor = "#d35050"
#    darkColor = "#212121"
#    lightColor = "#d6d6d6"
#    lightestColor = "#d3d3d3"
#    primaryColor = "#ffffff"